#!/bin/bash

# The sonic pi REPL needs extra support for 'require_relative' and 'include'
# Concatenate the support file first then any others.
# If this were smart it would parse the require_relative lines...

if [[ "$#" -eq 0 ]]
then
  echo Please give me some files to concatenate
  exit 1
fi

TARGET=out.spi
cat repl_support.rb $@ | grep -v sonic_stub > $TARGET
echo Concatenated to ${TARGET}, copying to pi...
scp $TARGET pi@pi:~pi/.sonic-pi/workspaces/default/two/1.spi
echo Done.
