#!/usr/bin/env ruby

# Run from local lib, not the installed bin/ script
DIR = File.dirname(__FILE__)
LIB = File.expand_path File.join(DIR, '..', 'lib', 'hap.rb')
require LIB

begin
    Hap.main File.basename(__FILE__)
rescue => e
    puts e.backtrace
end
